-- Script de Migración para extender la tabla Clientes

ALTER TABLE Clientes
ADD COLUMN correo VARCHAR(255),
ADD COLUMN id_tipo_cliente INT REFERENCES Tipos_Cliente(id_tipo_cliente),
ADD COLUMN id_comuna INT REFERENCES Comunas(id_comuna),
ADD COLUMN fecha_inicio_cliente DATE DEFAULT CURRENT_DATE,
ADD COLUMN id_canal_compra INT REFERENCES Canales_Compra(id_canal_compra),
ADD COLUMN id_frecuencia_compra INT REFERENCES Frecuencias_Compra(id_frecuencia_compra),
ADD COLUMN gasto_promedio_por_compra DECIMAL(10, 2),
ADD COLUMN ticket_promedio_total DECIMAL(10, 2),
ADD COLUMN preferencia_mix_berries BOOLEAN,
ADD COLUMN preferencia_pulpas BOOLEAN,
ADD COLUMN id_tipo_consumo INT REFERENCES Tipos_Consumo(id_tipo_consumo),
ADD COLUMN preferencia_envase TEXT,
ADD COLUMN intereses_promociones TEXT,
ADD COLUMN preferencia_alimentaria TEXT,
ADD COLUMN epoca_compra_preferida VARCHAR(50),
ADD COLUMN recibio_seguimiento_postventa BOOLEAN DEFAULT FALSE,
ADD COLUMN participo_promociones BOOLEAN DEFAULT FALSE,
ADD COLUMN tiene_deudas_pendientes BOOLEAN DEFAULT FALSE,
ADD COLUMN suscrito_newsletter BOOLEAN DEFAULT FALSE,
ADD COLUMN dejo_resenas BOOLEAN DEFAULT FALSE,
ADD COLUMN nivel_satisfaccion VARCHAR(50),
ADD COLUMN segmento_vip BOOLEAN DEFAULT FALSE,
ADD COLUMN coordenadas_geograficas TEXT,
ADD COLUMN fecha_cumpleanos DATE,
ADD COLUMN id_clasificacion_cliente INT REFERENCES Clasificaciones_Cliente(id_clasificacion_cliente),
ADD COLUMN etiquetas_comportamiento TEXT[]; -- Using TEXT[] for array of text
